version: 2
jobs:
  build:
    docker:
      - image: python:3.5
        environment:
          FLASK_CONFIG: testing
          DATABASE_URL: postgresql://ubuntu@localhost/circle_test?sslmode=disable
      - image: postgres:9.5
        environment:
          POSTGRES_USER: ubuntu
          POSTGRES_DB: circle_test
          POSTGRES_PASSWORD: ""

      working_directory: /home/ubuntu/circleci-docker-demo
      steps:
        - checkout
        - run:
            name: Install Python Requirements
            command: |
              pip install .
              pip install pytest
        - run:
            name: Run Tests
            command: |
              python setup.py test
